### PR TITLE
Remove incorrect Thread relationships

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Both patterns and brainstorm topics should use the wild card "is of"
relationship to threads.

Change-type: patch
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by joshbwlng** [comment]
@LucianBuzzo I'll take a look today and update any links using these older names so we can switch completely to "is of".

**Comment by LucianBuzzo** [comment]
I checked yesterday and the only one we needed to change was for brainstorm topics, I’ve already migrated the ones I found but might need to do it again. I just did it through the SDK and it was pretty simple.

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by joshbwlng** [comment]
> I checked yesterday and the only one we needed to change was for brainstorm topics, I’ve already migrated the ones I found but might need to do it again. I just did it through the SDK and it was pretty simple.

@LucianBuzzo We have `pattern` <-> `thread` links using the `is attached to`/`has attached` names in the db as well, see my comment above. Also, I think the `pattern-is-attached-to-thread`/`thread-has-attached-pattern` is out of scope for the `thread-is-of-*`/`*-has-thread` relationship. Unless I'm missing something, the link direction is the other way around.

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci rebase

**Comment by LucianBuzzo** [comment]
@balena-ci I self-certify!

**Pull request merged**
