### PR TITLE
Change insertCard to throw if the card already exists.

### PR DESCRIPTION
**Pull request by inwenc**
When inserting a contract when the contract already exists then it's an upsert call and not an insert. The client should call the patch Card (update) instead.

Change-type: minor
Signed-off-by: YingwenChen yingwenchen@balena.io

### CODE REVIEW

**Comment by inwenc** [comment]
@joshbwlng - how come this PR is not passing the builds if it's to merge to master?

**Comment by joshbwlng** [comment]
@inwenc Because its failing tests in the `ResinCI/docker/build` step. If you click the `Details` link next to it and dig through the `task: build` output, you can find the following:
```
sut_1       | FAIL test/integration/actions/action-create-event.spec.ts (6.35 s)
sut_1       |   ● action-create-event › should throw an error on attempt to insert existing contract
sut_1       | 
sut_1       |     expect(received).rejects.toThrow(expected)
sut_1       | 
sut_1       |     Expected constructor: JellyfishElementAlreadyExists
sut_1       |     Received constructor: Error
sut_1       | 
sut_1       |     Received message: "Contract card-10f52629-6bee-4972-a465-6ca71c8727e4 already exists"
sut_1       | 
sut_1       |           506 |
sut_1       |           507 | 		if (contract) {
sut_1       |         > 508 | 			throw new Error(`Contract ${object.slug || object.id} already exists`);
sut_1       |               | 			      ^
sut_1       |           509 | 		}
sut_1       |           510 |
sut_1       |           511 | 		if (typeof object.name !== 'string') {
sut_1       | 
sut_1       |       at Worker.insertCard (lib/index.ts:508:10)
sut_1       |                 at runMicrotasks (<anonymous>)
sut_1       |       at Object.handler (lib/actions/action-create-event.ts:43:18)
sut_1       |       at Object.<anonymous> (test/integration/actions/action-create-event.spec.ts:106:3)
sut_1       |       at Object.toThrow (node_modules/expect/build/index.js:285:22)
sut_1       |       at Object.<anonymous> (test/integration/actions/action-create-event.spec.ts:113:13)
sut_1       |           at runMicrotasks (<anonymous>)
sut_1       | 
sut_1       | Test Suites: 1 failed, 7 passed, 8 of 15 total
sut_1       | Tests:       1 failed, 147 passed, 148 total
```

I usually run tests locally before pushing so I don't have to wait for balenaCI to tell me something is wrong, much faster that way. Notes on how to run tests are in the main readme.

**Comment by joshbwlng** [comment]
And (unrelated to the above comment about failing tests), I believe AutumnDB should already be throwing an error if the contract already exists: https://github.com/product-os/autumndb/blob/master/lib/backend/postgres/cards.ts#L559

Maybe I'm missing some context? I'd like to see a failing test that shows that the system doesn't already throw an error on insert if a contract already exists.

**Comment by LucianBuzzo** [comment]
@joshbwlng @inwenc If it's already the case that AutumnDB will throw if the id/slug already exists then this whole code section can likely be omitted as it's crufty technical debt. 
@inwenc Can you try opening a separate PR that doesn't make any code changes, but just checks that the `insertCard` method throws if the contract already exists. We already appear to test this implicitly via `action-create-event` but something more explicit would be great.

**Comment by inwenc** [comment]
@LucianBuzzo - will do

**Comment by joshbwlng** [comment]
https://github.com/product-os/jellyfish-worker/pull/1493#issuecomment-1103282210

**Comment by inwenc** [comment]
Added tests in separate PR. AutumnDB already throws if slug exists.

**Pull request closed without merging**
